### ISSUE TITLE
can i customize reward and face of the snake?

### ISSUE THREAD

**Issue by Unimax** [ArthurFirmino/gym-battlesnake#2]
basically the rendering tells me agent don't know the head of the snake is it so?
also, I would like to customize the reward system is there any place where rewards in the current env are defined?

I understand i might have to go into the C++ implementation and modify i guess.

Also, can you let tell me why the `obs `shape is` : (N, 39, 39, 6)` why 6?

anyway, thanks for a good starting point to play with.

**Comment by ArthurFirmino** [comment]
The rendering code is gym_battlesnake/include/gamerenderer.h, and the relevant code would be this:
``` C++
                    sf::Color color;
                    unsigned tile_id = gi_->tileid(i,j);
                    if(tile_id == 0) {
                        color = sf::Color(159,159,159);
                    } else if(tile_id == FOOD_ID) {
                        color = sf::Color::Green;
                    } else {
                        uint32_t cid = static_cast<uint32_t>(tile_id);
                        cid = cid ^ 0xA2343434;
                        color = sf::Color(std::hash<uint32_t>{}(cid));
                    }
```
For each tile (i,j) it gets its tile_id which is either 0 for nothing, FOOD_ID, or some random number which is a snake's unique id. It doesn't distinguish between a snake's head or body. You could write a function like `ishead(int i, int j)` in gameinstance.h and check if any `Player` in `players_` has the first `Tile` of its `body_` at location (i, j). Then color that square differently, or maybe render a triangle.

Rewards are defined in gymbattlesnake.py:

```Python
    def step_wait(self):

        info = [{} for _ in range(self.n_envs)]
        dones = np.asarray([ False for _ in range(self.n_envs) ])
        rews = np.zeros((self.n_envs))

        infoptr = env_infoptr(self.ptr)
        for i in range(self.n_envs):
            if infoptr[i].ate:
                rews[i] += 0.1
            if infoptr[i].over:
                dones[i] = True
                info[i]['episode'] = {}
                if infoptr[i].alive:
                    rews[i] += 1.0 if infoptr[i].turn > 100 else 0.0
                    info[i]['episode']['r'] = 1.0 if infoptr[i].turn > 100 else 0.0
                else:
                    rews[i] -= 1.0
                    info[i]['episode']['r'] = -1.0
                info[i]['episode']['l'] = infoptr[i].turn

        return self.getobs(0), rews, dones, info
```
Currently it gives a small reward of 0.1 whenever it eats, a penalty of -1 if it loses (game is over and not alive), and a reward of 1 if it wins and the game lasted at least 100 turns (I believe this was to encourage the snake's to live longer and explore the later states of the game when the snake fill up more of the board).

Each of the 6 input layers codes different aspects of the game (as opposed to just feeding in a raw rendered frame of the game). The layers are built gamewrapper.cpp, and if you made a change in the python side you'd have to change the C++ side as well (and recompile), and vice versa. Here is a description of the layers seen in gamewrapper.cpp:

```C++
        /*
            layer0: snake health on heads {0,...,100}
            layer1: snake bodies {0,1}
            layer2: segment numbers {0,...,255}
            layer3: snake length >= player {0,1}
            layer4: food {0,1}
            layer5: gameboard {0,1}
        */
```

The layer's width and height are 39x39, however the player's head will always be at square (19,19) (this substantially sped up training). Also the game board size is variable, the width and height are random between 7 and 19 (this was to make the trained snake flexible). As well, each time it generates an input observation it will randomly flip x and y (this was to make sure the snakes didn't learn an arbitrary preference for a given corner).

**Comment by Unimax** [comment]
thanks for the full details. I appreciated.
one last question if you don't mind. 
which layer tells the network that this one snake is me.
also, i notice 

> player's head will always be at the square (19,19)

is not true
the layer one have health from all snakeheads at there locations.
layer 1 currently blocked by the body of snakes i guess. and layer 2 help see the direction of the snake i guess.
layer 3 possible incoming danger heads. 

basically I don't see any layer which tells the network of its own body.

where will be the logs for the tenserboard will be for the examples.

anyway, thanks a lot.

**Comment by ArthurFirmino** [comment]
The player's head should be centered in the layers (note that the render is positioned differently from the layers). This is part of the code that is used to assign a value to tile for layer a given layer `l`:

```C++
        auto assign = [this, model_i, env_i, head, ori](const Tile& xy, unsigned l, uint8_t val) {
            int x = (int(xy.first) - int(head.first)) * ((ori&1)?-1:1);
            int y = (int(xy.second) - int(head.second)) * ((ori&2)?-1:1);
            x += (LAYER_WIDTH/2);
            y += (LAYER_HEIGHT/2);
            if( x > 0 && x < LAYER_WIDTH && y > 0 && y < LAYER_HEIGHT)
                obss_[ model_i*(n_envs_*OBS_SIZE) + env_i*OBS_SIZE + x*(LAYER_HEIGHT*NUM_LAYERS) + y*NUM_LAYERS + l] = val;
        };
```

The two lines assigning `x` and `y` center the tile around the player's head.

I would suggest using something like matplotlib in Python to plot the individual layers to see what is going on. 

Ya layer 1 is just bodies {0,1}, layer 2 (if i recall correctly) is segments numbered starting from the tail (so that the head tile will also have the length of the snake). Yes, layer 3 was to hope it would avoid going into longer snakes' heads and lose.

**Comment by Unimax** [comment]
hi,  thanks again. I just noticed you are from uvic too let me know if we can have a chat at sunilkumar@uvic.ca. 
I think figured most of it, just didn't see that the player's head is the center. hmm, that makes sense.
